---
services:
  opencloud:
    volumes:
      - ./config/opencloud/apps.yaml:/etc/opencloud/apps.yaml
    depends_on:
      importer-init:
        condition: service_completed_successfully

  importer-init:
    image: ${WEB_EXTENSIONS_IMAGE:-opencloudeu/web-extensions}:${WEB_EXTENSION_IMPORTER_TAG:-importer-latest}
    user: root
    volumes:
      - opencloud-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /web/apps/importer /apps"]

  traefik:
    networks:
      opencloud-net:
        aliases:
          - ${COMPANION_DOMAIN:-companion.opencloud.test}

  companion:
    image: ${COMPANION_IMAGE:-transloadit/companion:6.2.2}
    networks:
      - opencloud-net
    environment:
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      COMPANION_DATADIR: /tmp/companion/
      COMPANION_DOMAIN: ${COMPANION_DOMAIN:-companion.opencloud.test}
      COMPANION_PROTOCOL: https
      COMPANION_UPLOAD_URLS: "^https://${OC_DOMAIN:-cloud.opencloud.test}/"
      COMPANION_ONEDRIVE_KEY: "${COMPANION_ONEDRIVE_KEY}"
      COMPANION_ONEDRIVE_SECRET: "${COMPANION_ONEDRIVE_SECRET}"
    volumes:
      - companion-data:/tmp/companion/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.companion.entrypoints=https"
      - "traefik.http.routers.companion.rule=Host(`${COMPANION_DOMAIN:-companion.opencloud.test}`)"
      - "traefik.http.routers.companion.service=companion"
      - "traefik.http.routers.companion.middlewares=hsts-header"
      - "traefik.http.routers.companion.${TRAEFIK_SERVICES_TLS_CONFIG}"
      - "traefik.http.services.companion.loadbalancer.server.port=3020"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

volumes:
  companion-data:
