---
services:
  opencloud:
    depends_on:
      jsonviewer-init:
        condition: service_completed_successfully

  jsonviewer-init:
    image: ${WEB_EXTENSIONS_IMAGE:-opencloudeu/web-extensions}:${WEB_EXTENSION_JSONVIEWER_TAG:-json-viewer-latest}
    user: root
    volumes:
      - opencloud-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /web/apps/json-viewer /apps"]
