---
services:
  opencloud:
    depends_on:
      pastebin-init:
        condition: service_completed_successfully

  pastebin-init:
    image: ${WEB_EXTENSIONS_IMAGE:-opencloudeu/web-extensions}:${WEB_EXTENSION_PASTEBIN_TAG:-pastebin-latest}
    user: root
    volumes:
      - opencloud-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /web/apps/pastebin /apps"]
