#!/usr/bin/env node

// scripts/gettext_compile.ts
import chalk from "chalk";
import commandLineArgs from "command-line-args";
import fsPromises2 from "fs/promises";
import path2 from "path";

// scripts/compile.ts
import Pofile from "pofile";
import fsPromises from "fs/promises";
var sanitizePoData = (poItems) => {
  const messages = {};
  for (let item of poItems) {
    const ctx = item.msgctxt || "";
    if (item.msgstr[0] && item.msgstr[0].length > 0 && !item.flags.fuzzy && !item.obsolete) {
      if (!messages[item.msgid]) {
        messages[item.msgid] = {};
      }
      messages[item.msgid][ctx] = item.msgstr.length === 1 ? item.msgstr[0] : item.msgstr;
    }
  }
  for (let key in messages) {
    if (Object.keys(messages[key]).length === 1 && messages[key][""]) {
      messages[key] = messages[key][""];
    }
  }
  return messages;
};
var po2json = (poContent) => {
  const catalog = Pofile.parse(poContent);
  if (!catalog.headers.Language) {
    throw new Error("No Language headers found!");
  }
  return {
    headers: catalog.headers,
    messages: sanitizePoData(catalog.items)
  };
};
var compilePoFiles = async (localesPaths) => {
  const translations = {};
  await Promise.all(
    localesPaths.map(async (lp) => {
      const fileContent = await fsPromises.readFile(lp, { encoding: "utf-8" });
      const data = po2json(fileContent);
      const lang = data.headers.Language;
      if (lang && !translations[lang]) {
        translations[lang] = data.messages;
      } else {
        Object.assign(translations[data.headers.Language], data.messages);
      }
    })
  );
  return translations;
};

// scripts/config.ts
import { lilconfig } from "lilconfig";
import path from "path";
var loadConfig = async (cliArgs) => {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o;
  const configSearcher = lilconfig("gettext", {
    searchPlaces: ["gettext.config.js", "gettext.config.cjs", "gettext.config.mjs", "package.json"]
  });
  let configRes;
  if (cliArgs == null ? void 0 : cliArgs.config) {
    configRes = await configSearcher.load(cliArgs.config);
    if (!configRes) {
      throw new Error(`Config not found: ${cliArgs.config}`);
    }
  } else {
    configRes = await configSearcher.search();
  }
  const config = (_a = configRes == null ? void 0 : configRes.config) != null ? _a : {};
  const languagePath = ((_b = config.output) == null ? void 0 : _b.path) || "./src/language";
  const joinPath = (inputPath) => path.join(languagePath, inputPath);
  const joinPathIfRelative = (inputPath) => {
    if (!inputPath) {
      return void 0;
    }
    return path.isAbsolute(inputPath) ? inputPath : path.join(languagePath, inputPath);
  };
  return {
    input: {
      path: ((_c = config.input) == null ? void 0 : _c.path) || "./src",
      include: ((_d = config.input) == null ? void 0 : _d.include) || ["**/*.js", "**/*.ts", "**/*.vue"],
      exclude: ((_e = config.input) == null ? void 0 : _e.exclude) || [],
      parserOptions: (_f = config.input) == null ? void 0 : _f.parserOptions
    },
    output: {
      path: languagePath,
      potPath: joinPathIfRelative((_g = config.output) == null ? void 0 : _g.potPath) || joinPath("./messages.pot"),
      jsonPath: joinPathIfRelative((_h = config.output) == null ? void 0 : _h.jsonPath) || (((_i = config.output) == null ? void 0 : _i.splitJson) ? joinPath("./") : joinPath("./translations.json")),
      locales: ((_j = config.output) == null ? void 0 : _j.locales) || ["en"],
      flat: ((_k = config.output) == null ? void 0 : _k.flat) === void 0 ? true : config.output.flat,
      linguas: ((_l = config.output) == null ? void 0 : _l.linguas) === void 0 ? true : config.output.linguas,
      splitJson: ((_m = config.output) == null ? void 0 : _m.splitJson) === void 0 ? false : config.output.splitJson,
      fuzzyMatching: ((_n = config.output) == null ? void 0 : _n.fuzzyMatching) === void 0 ? true : config.output.fuzzyMatching,
      locations: ((_o = config.output) == null ? void 0 : _o.locations) === void 0 ? true : config.output.locations
    }
  };
};

// scripts/gettext_compile.ts
var optionDefinitions = [{ name: "config", alias: "c", type: String }];
var options;
try {
  options = commandLineArgs(optionDefinitions);
} catch (e) {
  console.error(e);
  process.exit(1);
}
(async () => {
  const config = await loadConfig(options);
  console.info(`Language directory: ${chalk.blueBright(config.output.path)}`);
  console.info(`Locales: ${chalk.blueBright(config.output.locales)}`);
  console.info();
  const localesPaths = config.output.locales.map(
    (loc) => config.output.flat ? path2.join(config.output.path, `${loc}.po`) : path2.join(config.output.path, `${loc}/app.po`)
  );
  await fsPromises2.mkdir(config.output.path, { recursive: true });
  const jsonRes = await compilePoFiles(localesPaths);
  console.info(`${chalk.green("Compiled json")}: ${chalk.grey(JSON.stringify(jsonRes))}`);
  console.info();
  if (config.output.splitJson) {
    await Promise.all(
      config.output.locales.map(async (locale) => {
        const outputPath = path2.join(config.output.jsonPath, `${locale}.json`);
        await fsPromises2.writeFile(
          outputPath,
          JSON.stringify({
            [locale]: jsonRes[locale]
          })
        );
        console.info(`${chalk.green("Created")}: ${chalk.blueBright(outputPath)}`);
      })
    );
  } else {
    const outputPath = config.output.jsonPath;
    await fsPromises2.writeFile(outputPath, JSON.stringify(jsonRes));
    console.info(`${chalk.green("Created")}: ${chalk.blueBright(outputPath)}`);
  }
})();
