// Combine the logic layer (#set / #let / #show) with the serialized ProseMirror
// content into a full Typst source string. One-way only.

import type { Node as PMNode } from '@tiptap/pm/model';
import type { DocLogic, DocStyle, LetBinding, PageSize, ShowRule } from './model';
import { CALLOUT_SRC } from './model';
import { serializeContent, escapeMarkup } from './serialize';

const PAPER: Record<PageSize, string> = { a4: 'a4', 'us-letter': 'us-letter', a5: 'a5' };

function quote(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/** A hex color like #1c7ed6 -> rgb("#1c7ed6"); anything else passed through. */
function color(v: string): string {
  const t = v.trim();
  return /^#[0-9a-fA-F]{3,8}$/.test(t) ? `rgb(${quote(t)})` : t;
}

function genStyle(style: DocStyle): string {
  const lines: string[] = [];
  const pageArgs: string[] = [`paper: ${quote(PAPER[style.page.paper])}`, `margin: ${style.page.marginCm}cm`];
  if (style.page.columns && style.page.columns > 1) pageArgs.push(`columns: ${style.page.columns}`);
  if (style.page.numbering) pageArgs.push(`numbering: ${style.page.numberingFormat ?? '"1"'}`);
  if (style.page.header?.trim()) pageArgs.push(`header: [${escapeMarkup(style.page.header.trim())}]`);
  if (style.page.footer?.trim()) pageArgs.push(`footer: [${escapeMarkup(style.page.footer.trim())}]`);
  if (style.page.extra) pageArgs.push(...style.page.extra);
  lines.push(`#set page(${pageArgs.join(', ')})`);
  const textArgs: string[] = [`size: ${style.text.sizePt}pt`];
  if (style.text.font.trim() !== '') textArgs.unshift(`font: ${quote(style.text.font.trim())}`);
  if (style.text.extra) textArgs.push(...style.text.extra);
  lines.push(`#set text(${textArgs.join(', ')})`);
  const parArgs: string[] = [`leading: ${style.par.leadingEm}em`, `justify: ${style.par.justify}`];
  if (style.par.extra) parArgs.push(...style.par.extra);
  lines.push(`#set par(${parArgs.join(', ')})`);
  if (style.page.headingNumbering || style.page.headingExtra) {
    const headArgs: string[] = [];
    if (style.page.headingNumbering) headArgs.push(`numbering: ${style.page.headingNumberingFormat ?? '"1.1"'}`);
    if (style.page.headingExtra) headArgs.push(...style.page.headingExtra);
    lines.push(`#set heading(${headArgs.join(', ')})`);
  }
  return lines.join('\n');
}

function genLet(b: LetBinding): string {
  if (b.kind === 'raw') return b.code.trim();
  const name = b.name.trim() || 'unnamed';
  if (b.kind === 'value') return `#let ${name} = ${b.code.trim() || '""'}`;
  const body = (b.code.trim() || 'body')
    .split('\n')
    .map((l) => (l.length ? '  ' + l : l))
    .join('\n');
  return `#let ${name}(body) = {\n${body}\n}`;
}

function genShow(s: ShowRule): string {
  let selector: string;
  if (s.target === 'custom') selector = (s.customSelector ?? '').trim() || 'heading';
  else if (s.target === 'heading' && s.level != null) selector = `heading.where(level: ${s.level})`;
  else selector = s.target;

  if (s.kind === 'function') {
    const body = (s.body ?? '').trim() || 'it';
    return `#show ${selector}: it => {\n${body.split('\n').map((l) => (l.length ? '  ' + l : l)).join('\n')}\n}`;
  }

  const props: string[] = [];
  if (s.props.fill.trim()) props.push(`fill: ${color(s.props.fill)}`);
  if (s.props.sizePt != null) props.push(`size: ${s.props.sizePt}pt`);
  if (s.props.weight !== 'inherit') props.push(`weight: ${quote(s.props.weight)}`);
  if (s.props.style !== 'inherit') props.push(`style: ${quote(s.props.style)}`);

  // Nothing to set => emphasize visibly so the rule is never a no-op surprise.
  const body = props.length ? `set text(${props.join(', ')})` : 'set text()';
  return `#show ${selector}: ${body}`;
}

function contentUsesCallout(content: PMNode): boolean {
  let found = false;
  content.descendants((n) => { if (n.type.name === 'callout') found = true; });
  return found;
}

export function generate(logic: DocLogic, content: PMNode): string {
  const parts: string[] = [];
  parts.push('// Generated by typst-wysiwyg. Edits are re-imported (best-effort).');
  // Preserved imports / unmodeled preamble go first (imports must precede use).
  if (logic.extra?.length) {
    parts.push('');
    parts.push('// --- imports & preamble ---');
    parts.push(logic.extra.join('\n'));
  }
  parts.push('');
  parts.push(genStyle(logic.style));
  parts.push('');
  // The callout component normally lives in logic.lets (so it's visible and
  // editable). Fall back to the built-in only for legacy documents that use a
  // callout but carry no binding for it.
  if (!logic.lets.some((l) => l.name === 'callout') && contentUsesCallout(content)) parts.push(CALLOUT_SRC);

  if (logic.lets.length) {
    parts.push('');
    parts.push('// --- definitions ---');
    parts.push(logic.lets.map(genLet).join('\n'));
  }
  if (logic.shows.length) {
    parts.push('');
    parts.push('// --- show rules ---');
    parts.push(logic.shows.map(genShow).join('\n'));
  }

  parts.push('');
  parts.push('// --- content ---');
  parts.push(serializeContent(content));

  if (logic.bibliography && logic.bibliography.content.trim()) {
    const ext = logic.bibliography.format === 'yaml' ? 'yml' : 'bib';
    parts.push('');
    parts.push(`#bibliography(${quote(`/refs.${ext}`)})`);
  }

  parts.push('');
  return parts.join('\n');
}

/** The VFS path the bibliography file is mapped to for a given format. */
export function bibPath(format: 'bibtex' | 'yaml'): string {
  return `/refs.${format === 'yaml' ? 'yml' : 'bib'}`;
}

/** Pull citation keys out of a BibTeX or Hayagriva-YAML source. */
export function extractCitationKeys(bib: { format: 'bibtex' | 'yaml'; content: string }): string[] {
  const keys: string[] = [];
  if (bib.format === 'bibtex') {
    for (const m of bib.content.matchAll(/@\w+\s*\{\s*([^,\s}]+)/g)) keys.push(m[1]);
  } else {
    // Hayagriva: top-level (column-0) `key:` entries.
    for (const line of bib.content.split('\n')) {
      const m = line.match(/^([A-Za-z0-9_:.-]+):\s*$/);
      if (m) keys.push(m[1]);
    }
  }
  return keys;
}
